### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dunyakirkali**
I added a link to the OneSky Elixir client.

### CODE REVIEW

**Comment by ryan-dan-coleman** [comment]
Hi thanks for adding this Elixir Client. I tested and noticed two things:

- The hackney version should be updated. I needed to override this dependency before making calls, see here for details: https://github.com/benoitc/hackney/issues/591

- As mentioned in the readme, some important endpoints are not yet implemented such UPLOAD and EXPORT

If these can be updated then I will merge the PR.

**Comment by dunyakirkali** [comment]
@ryan-dan-coleman Done and Done! :)

**Comment by ryan-dan-coleman** [comment]
Thanks! 

Exporting is working as expected.

For uploading files, can you check the content-type used in this request? When attempting to perform a file import, I get this response:
`"meta" => %{"message" => "String file not found", "status" => 404}`

I noticed the content-type is "application/json" but I believe this should be "multipart/form-data".

Here is my call:

`  def import_file do
    translation_file = "fixture/files/ex4.yml" |> File.read! |> Base.encode64()
    file = [
        %{
          "file" => translation_file,
          "file_format" => "RUBY_YAML",
          "locale" => "en",
          "is_keeping_all_strings" => true,
          "is_allow_translation_same_as_original" => false
        }
      ]
    client = Onesky.client()
    return = Onesky.File.upload_file(client, @project_id, file)
  end`

**Comment by dunyakirkali** [comment]
@ryan-dan-coleman ah!, good catch. I'll get it fixed tomorrow and give u a sign once it's done.

**Comment by dunyakirkali** [comment]
@ryan-dan-coleman fixed!

**Comment by ryan-dan-coleman** [comment]
Thanks Dunya! Merged :)

**Pull request merged**
